package com.example.gestordepeliculas.domain.model.movieserie

import com.example.gestordepeliculas.data.remote.models.Ads
import com.example.gestordepeliculas.data.remote.models.Buy
import com.example.gestordepeliculas.data.remote.models.CountryProviderResults
import com.example.gestordepeliculas.data.remote.models.Flatrate
import com.example.gestordepeliculas.data.remote.models.Rent
import com.example.gestordepeliculas.data.remote.models.WatchProviders

data class CountryProviderResultsModel(
    val AE: WatchProvidersModel? = null,
    val AL: WatchProvidersModel? = null,
    val AR: WatchProvidersModel? = null,
    val AT: WatchProvidersModel? = null,
    val AU: WatchProvidersModel? = null,
    val AZ: WatchProvidersModel? = null,
    val BA: WatchProvidersModel? = null,
    val BB: WatchProvidersModel? = null,
    val BE: WatchProvidersModel? = null,
    val BG: WatchProvidersModel? = null,
    val BH: WatchProvidersModel? = null,
    val BO: WatchProvidersModel? = null,
    val BR: WatchProvidersModel? = null,
    val BS: WatchProvidersModel? = null,
    val CA: WatchProvidersModel? = null,
    val CH: WatchProvidersModel? = null,
    val CL: WatchProvidersModel? = null,
    val CO: WatchProvidersModel? = null,
    val CR: WatchProvidersModel? = null,
    val CV: WatchProvidersModel? = null,
    val CY: WatchProvidersModel? = null,
    val CZ: WatchProvidersModel? = null,
    val DE: WatchProvidersModel? = null,
    val DK: WatchProvidersModel? = null,
    val DO: WatchProvidersModel? = null,
    val EC: WatchProvidersModel? = null,
    val EE: WatchProvidersModel? = null,
    val EG: WatchProvidersModel? = null,
    val ES: WatchProvidersModel? = null,
    val FI: WatchProvidersModel? = null,
    val FJ: WatchProvidersModel? = null,
    val FR: WatchProvidersModel? = null,
    val GB: WatchProvidersModel? = null,
    val GF: WatchProvidersModel? = null,
    val GI: WatchProvidersModel? = null,
    val GH: WatchProvidersModel? = null,
    val GR: WatchProvidersModel? = null,
    val GT: WatchProvidersModel? = null,
    val HK: WatchProvidersModel? = null,
    val HN: WatchProvidersModel? = null,
    val HR: WatchProvidersModel? = null,
    val HU: WatchProvidersModel? = null,
    val ID: WatchProvidersModel? = null,
    val IE: WatchProvidersModel? = null,
    val IL: WatchProvidersModel? = null,
    val IN: WatchProvidersModel? = null,
    val IQ: WatchProvidersModel? = null,
    val IS: WatchProvidersModel? = null,
    val IT: WatchProvidersModel? = null,
    val JM: WatchProvidersModel? = null,
    val JO: WatchProvidersModel? = null,
    val JP: WatchProvidersModel? = null,
    val KR: WatchProvidersModel? = null,
    val KW: WatchProvidersModel? = null,
    val LB: WatchProvidersModel? = null,
    val LI: WatchProvidersModel? = null,
    val LT: WatchProvidersModel? = null,
    val LU: WatchProvidersModel? = null,
    val LV: WatchProvidersModel? = null,
    val MD: WatchProvidersModel? = null,
    val MK: WatchProvidersModel? = null,
    val MT: WatchProvidersModel? = null,
    val MU: WatchProvidersModel? = null,
    val MX: WatchProvidersModel? = null,
    val MY: WatchProvidersModel? = null,
    val MZ: WatchProvidersModel? = null,
    val NI: WatchProvidersModel? = null,
    val NL: WatchProvidersModel? = null,
    val NO: WatchProvidersModel? = null,
    val NZ: WatchProvidersModel? = null,
    val OM: WatchProvidersModel? = null,
    val PA: WatchProvidersModel? = null,
    val PE: WatchProvidersModel? = null,
    val PH: WatchProvidersModel? = null,
    val PK: WatchProvidersModel? = null,
    val PL: WatchProvidersModel? = null,
    val PS: WatchProvidersModel? = null,
    val PT: WatchProvidersModel? = null,
    val PY: WatchProvidersModel? = null,
    val QA: WatchProvidersModel? = null,
    val RO: WatchProvidersModel? = null,
    val RS: WatchProvidersModel? = null,
    val RU: WatchProvidersModel? = null,
    val SA: WatchProvidersModel? = null,
    val SE: WatchProvidersModel? = null,
    val SG: WatchProvidersModel? = null,
    val SI: WatchProvidersModel? = null,
    val SK: WatchProvidersModel? = null,
    val SM: WatchProvidersModel? = null,
    val SV: WatchProvidersModel? = null,
    val TH: WatchProvidersModel? = null,
    val TR: WatchProvidersModel? = null,
    val TT: WatchProvidersModel? = null,
    val TW: WatchProvidersModel? = null,
    val UA: WatchProvidersModel? = null,
    val UG: WatchProvidersModel? = null,
    val US: WatchProvidersModel? = null,
    val UY: WatchProvidersModel? = null,
    val VE: WatchProvidersModel? = null,
    val YE: WatchProvidersModel? = null,
    val ZA: WatchProvidersModel? = null,
)

fun CountryProviderResults.toDomain() = CountryProviderResultsModel(
    AE = AE?.toDomain(),
    AL = AL?.toDomain(),
    AR = AR?.toDomain(),
    AT = AT?.toDomain(),
    AU = AU?.toDomain(),
    AZ = AZ?.toDomain(),
    BA = BA?.toDomain(),
    BB = BB?.toDomain(),
    BE = BE?.toDomain(),
    BG = BG?.toDomain(),
    BH = BH?.toDomain(),
    BO = BO?.toDomain(),
    BR = BR?.toDomain(),
    BS = BS?.toDomain(),
    CA = CA?.toDomain(),
    CH = CH?.toDomain(),
    CL = CL?.toDomain(),
    CO = CO?.toDomain(),
    CR = CR?.toDomain(),
    CV = CV?.toDomain(),
    CY = CY?.toDomain(),
    CZ = CZ?.toDomain(),
    DE = DE?.toDomain(),
    DK = DK?.toDomain(),
    DO = DO?.toDomain(),
    EC = EC?.toDomain(),
    EE = EE?.toDomain(),
    EG = EG?.toDomain(),
    ES = ES?.toDomain(),
    FI = FI?.toDomain(),
    FJ = FJ?.toDomain(),
    FR = FR?.toDomain(),
    GB = GB?.toDomain(),
    GF = GF?.toDomain(),
    GI = GI?.toDomain(),
    GH = GH?.toDomain(),
    GR = GR?.toDomain(),
    GT = GT?.toDomain(),
    HK = HK?.toDomain(),
    HN = HN?.toDomain(),
    HR = HR?.toDomain(),
    HU = HU?.toDomain(),
    ID = ID?.toDomain(),
    IE = IE?.toDomain(),
    IL = IL?.toDomain(),
    IN = IN?.toDomain(),
    IQ = IQ?.toDomain(),
    IS = IS?.toDomain(),
    IT = IT?.toDomain(),
    JM = JM?.toDomain(),
    JO = JO?.toDomain(),
    JP = JP?.toDomain(),
    KR = KR?.toDomain(),
    KW = KW?.toDomain(),
    LB = LB?.toDomain(),
    LI = LI?.toDomain(),
    LT = LT?.toDomain(),
    LU = LU?.toDomain(),
    LV = LV?.toDomain(),
    MD = MD?.toDomain(),
    MK = MK?.toDomain(),
    MT = MT?.toDomain(),
    MU = MU?.toDomain(),
    MX = MX?.toDomain(),
    MY = MY?.toDomain(),
    MZ = MZ?.toDomain(),
    NI = NI?.toDomain(),
    NL = NL?.toDomain(),
    NO = NO?.toDomain(),
    NZ = NZ?.toDomain(),
    OM = OM?.toDomain(),
    PA = PA?.toDomain(),
    PE = PE?.toDomain(),
    PH = PH?.toDomain(),
    PK = PK?.toDomain(),
    PL = PL?.toDomain(),
    PS = PS?.toDomain(),
    PT = PT?.toDomain(),
    PY = PY?.toDomain(),
    QA = QA?.toDomain(),
    RO = RO?.toDomain(),
    RS = RS?.toDomain(),
    RU = RU?.toDomain(),
    SA = SA?.toDomain(),
    SE = SE?.toDomain(),
    SG = SG?.toDomain(),
    SI = SI?.toDomain(),
    SK = SK?.toDomain(),
    SM = SM?.toDomain(),
    SV = SV?.toDomain(),
    TH = TH?.toDomain(),
    TR = TR?.toDomain(),
    TT = TT?.toDomain(),
    TW = TW?.toDomain(),
    UA = UA?.toDomain(),
    UG = UG?.toDomain(),
    US = US?.toDomain(),
    UY = UY?.toDomain(),
    VE = VE?.toDomain(),
    YE = YE?.toDomain(),
    ZA = ZA?.toDomain(),
)

data class WatchProvidersModel(
    val link: String?,
    val rent: List<RentModel>,
    val ads: List<AdsModel>,
    val flatrate: List<FlatrateModel>,
    val buy: List<BuyModel>
)
fun WatchProviders.toDomain() = WatchProvidersModel(
    link = link,
    rent = rent?.map { it.toDomain() } ?: emptyList(),
    ads = ads?.map { it.toDomain() } ?: emptyList(),
    flatrate = flatrate?.map { it.toDomain() } ?: emptyList(),
    buy = buy?.map { it.toDomain() } ?: emptyList(),
)


data class RentModel(
    val logo_path: String?,
    val provider_id: Int?,
    val provider_name: String?,
    val display_priority: Int?,
)
fun Rent.toDomain() = RentModel(
    logo_path = logo_path,
    provider_id = provider_id,
    provider_name = provider_name,
    display_priority = display_priority,
)

data class AdsModel(
    val logo_path: String?,
    val provider_id: Int?,
    val provider_name: String?,
    val display_priority: Int?,
)
fun Ads.toDomain() = AdsModel(
    logo_path = logo_path,
    provider_id = provider_id,
    provider_name = provider_name,
    display_priority = display_priority,
)

data class FlatrateModel(
    val logo_path: String?,
    val provider_id: Int?,
    val provider_name: String?,
    val display_priority: Int?,
)
fun Flatrate.toDomain() = FlatrateModel(
    logo_path = logo_path,
    provider_id = provider_id,
    provider_name = provider_name,
    display_priority = display_priority,
)

data class BuyModel(
    val logo_path: String?,
    val provider_id: Int?,
    val provider_name: String?,
    val display_priority: Int?,
)
fun Buy.toDomain() = BuyModel(
    logo_path = logo_path,
    provider_id = provider_id,
    provider_name = provider_name,
    display_priority = display_priority,
)



